openapi: 3.0.3
info:
  title: User API
  description: API to retrieve user information
  version: 0.0.1
tags:
  - name: users
    description: Everything about users
paths:
  /v1/users:
    post:
      operationId: createUser
      summary: Create User
      description: Endpoint to populate user details
      tags:
        - users
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        "204":
          description: User created
        "400":
          description: Bad request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      operationId: findUserByLastName
      summary: Find User(s) with matching last name
      description: Retrieve an account access consent and check its status.
      tags:
        - users
      parameters:
        - name: lastName
          in: query
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: User(s) found
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"
        "400":
          description: Bad request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
          minLength: 1
        email:
          type: string
      required:
        - lastName